version: 2
registries:
  git-bitbucket-org:
    type: git
    url: https://bitbucket.org
    username: derteaser@gmail.com
    password: "${{secrets.GIT_BITBUCKET_ORG_PASSWORD}}"
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - derteaser
  assignees:
  - derteaser
  registries:
  - git-bitbucket-org
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - derteaser
  registries:
  - git-bitbucket-org
