title: Site

options:
  update:
    *: false
    admin: true

tabs:
  content:
    label: Inhalte
    columns:
      navigationPages:
        width: 1/3
        sections:
          pages: true
      videoPages:
        width: 2/3
        sections:
          videos:
            type: pages
            headline: Videos
            templates: video
            parent: site.find("watch")
            sortBy: created desc
            status: unlisted
            layout: cards
            info: " {{ page.created.toDate('d.m.Y') }}"
            image:
              ratio: 16/9
  settings:
    label: Einstellungen
    fields:
      cloudinarySettings:
        label: Cloudinary
        type: headline
        numbered: false
      cloudinary_cloud_name:
        type: text
        label: Cloud Name
      cloudinary_key:
        type: text
        label: API Key
        width: 1/2
      cloudinary_secret:
        type: text
        label: API Secret
        width: 1/2
