name: Deploy to Live

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@d0696f9f8bc3b0456d759159fadc1bb4f31f1e10
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Create local changes
      run: |
        composer install --no-dev
        yarn install
        yarn run build
    - name: Commit and push local changes
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: Apply theme changes

