name: Deploy to Live

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@d0696f9f8bc3b0456d759159fadc1bb4f31f1e10
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Create local changes
      run: |
        composer install --no-dev
        yarn install
        yarn run build
    - name: Commit and push local changes
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: Apply theme changes
    /*- name: Pulling repo from production server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd katholikenrat/frontend
          git pull
          /usr/bin/php8.0-cli composer.phar install --no-dev
          /usr/bin/php8.0-cli artisan lit:permissions
          /usr/bin/php8.0-cli artisan icons:cache
          # /usr/bin/php8.0-cli artisan optimize -q
    - uses: actions/checkout@v3
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production*/

